const data = {
  title: "홈투데이",
  screen_name: "TODAY",
  view_event_logging: {},
  logging: {
    SCREEN: "TODAY",
  },
  components: [
    {
      component_id: 128,
      type: {
        header: null,
        item_list: "TWO_COL_CARD_LIST",
        footer: null,
      },
      logging: {
        analytics: {
          LIST_ID: "today_recommend",
        },
        ably_only_log: {
          list_id: "today_recommend",
        },
      },
      entity: {
        header: null,
        item_list: [
          {
            type: "GOODS_CARD",
            item_entity: {
              item: {
                sno: 52576842,
                name: "각이당 수제비빵 15종 골라담기",
                image:
                  "https://d3ha2047wt6x28.cloudfront.net/dbskzPcBTPs/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2NlY2I1YzE1MjgzNDdiNDA4NWFmNzgxMmJhMDBlYWQ4LmpwZw",
                market_sno: 97042,
                market_name: "각이당",
                market_type: "라이프",
                delivery_type: "standard",
                sell_count: 2175,
                discount_rate: 0,
                first_page_rendering: {
                  goods_name: "각이당 수제비빵 15종 골라담기",
                  market_name: "각이당",
                  cover_image:
                    "https://d3ha2047wt6x28.cloudfront.net/xdck56rpW_8/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjUwOTA0XzE3NTY5Nzg1ODAyNzYyODhtLmdpZg",
                  market_image: null,
                  discount_rate: 0,
                  original_price: 4500,
                  price: 4500,
                },
                is_new: false,
                price: 4500,
                like: {
                  goods_sno: 52576842,
                  is_liked: false,
                  folder_sno: null,
                  referrer: {
                    list_id: "today_recommend",
                    list_index: 3,
                  },
                },
                ad: null,
                on_return: {
                  type: "INJECT",
                  data: {
                    url: "goods/52576842/recommend_related_goods_by_click_for_today/?from=TODAY",
                  },
                },
                category_name: "떡/베이커리",
                feedback_type: "contain_icon",
                remote_deeplink: null,
              },
              logging: {
                ably_only_log: {
                  schema_name: "Goods",
                  list_id: "today_recommend",
                  list_index: 3,
                  pool: "best",
                  goods_sno: 52576842,
                },
                analytics: {
                  IS_COPY_TARGET_GOODS: false,
                  GOODS_SNO: "52576842",
                  GOODS_NAME: "각이당 수제비빵 15종 골라담기",
                  MARKET_TYPE: "라이프",
                  MARKET_SNO: "97042",
                  MARKET_NAME: "각이당",
                  CATEGORY_SNO: "666",
                  CATEGORY_NAME: "떡/베이커리",
                  STANDARD_CATEGORY_SNO: "346",
                  STANDARD_CATEGORY_NAME: "빵",
                  DISCOUNT_RATE: 0,
                  SALES_PRICE: 4500,
                  SALES_PRICE_RANGE: "1~5,000",
                  IS_NEW: "0",
                  DELIVERY_TYPE: "standard",
                  IS_AD: "0",
                  LIST_PARAMS: null,
                  MARKET_TYPE_SNO: "2",
                  REVIEW_COUNT: 0,
                  REVIEW_COUNT_RANGE: "0",
                  REVIEW_RATING: 0,
                  LIKES_COUNT: 401,
                  LIKES_COUNT_RANGE: "401~450",
                  PROMOTION_TAG: ["FIRST_PURCHASE_BENEFIT"],
                  HAS_AWARD: false,
                  IS_ONLY_ABLY: false,
                  IMAGE_BADGE_LIST: [],
                  LIST_ID: "today_recommend",
                  LIST_INDEX: 3,
                },
              },
              render: {
                contents: ["PRICE", "NAME", "STORE", "NUDGING", "CHIPS"],
                size: "MEDIUM",
                data: {
                  image: {
                    url: "https://d3ha2047wt6x28.cloudfront.net/dbskzPcBTPs/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2NlY2I1YzE1MjgzNDdiNDA4NWFmNzgxMmJhMDBlYWQ4LmpwZw",
                    use_animation: true,
                    ratio: 1.2,
                  },
                  name: "각이당 수제비빵 15종 골라담기",
                  price: "4,500",
                  has_ad_badge: false,
                  name_lines: 1,
                  discount_rate: null,
                  closed_reason: null,
                  image_badge: null,
                  image_badge_width: null,
                  image_badge_height: null,
                  image_badge_list: [],
                  chips: [
                    {
                      meta: {
                        text_style: "subtitle6",
                        text_color: "#FF5160",
                        bg_color: "#FFEFF2",
                        border_color: "#FFEFF2",
                        border_width: 1,
                        rounded_corner_radius: 2,
                      },
                      name: "첫구매 혜택",
                      type: "DITTO_TEXT",
                    },
                  ],
                  store_text: "각이당",
                  nudging_text: "2,175개 구매중",
                  ranking: null,
                  actions: ["LIKE"],
                  discount_end_text: null,
                  top_nudging_text: null,
                  price_description: null,
                  today_delivery_order_deadline_time: null,
                },
              },
            },
          },
          {
            type: "GOODS_CARD",
            item_entity: {
              item: {
                sno: 52500935,
                name: "틴베이크 에이블리 팝업 라인업 14종 골라담기",
                image:
                  "https://d3ha2047wt6x28.cloudfront.net/vPyruvzrNvY/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2ZiMjA3OTQ2ZGJlNGIxYTU0ZWJjMTE0OGU4OWFiZGRjLmpwZw",
                market_sno: 64903,
                market_name: "틴베이크",
                market_type: "라이프",
                delivery_type: "standard",
                sell_count: 1973,
                discount_rate: 11,
                first_page_rendering: {
                  goods_name: "틴베이크 에이블리 팝업 라인업 14종 골라담기",
                  market_name: "틴베이크",
                  cover_image:
                    "https://d3ha2047wt6x28.cloudfront.net/IZjaEwloUnQ/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjUwOTEyXzE3NTc2NTI0OTM5MTExNzhtLmpwZw",
                  market_image: null,
                  discount_rate: 11,
                  original_price: 3600,
                  price: 3200,
                },
                is_new: false,
                price: 3200,
                like: {
                  goods_sno: 52500935,
                  is_liked: false,
                  folder_sno: null,
                  referrer: {
                    list_id: "today_recommend",
                    list_index: 4,
                  },
                },
                ad: null,
                on_return: {
                  type: "INJECT",
                  data: {
                    url: "goods/52500935/recommend_related_goods_by_click_for_today/?from=TODAY",
                  },
                },
                category_name: "과자/쿠키",
                feedback_type: "contain_icon",
                remote_deeplink: null,
              },
              logging: {
                ably_only_log: {
                  schema_name: "Goods",
                  list_id: "today_recommend",
                  list_index: 4,
                  pool: "best",
                  goods_sno: 52500935,
                },
                analytics: {
                  IS_COPY_TARGET_GOODS: false,
                  GOODS_SNO: "52500935",
                  GOODS_NAME: "틴베이크 에이블리 팝업 라인업 14종 골라담기",
                  MARKET_TYPE: "라이프",
                  MARKET_SNO: "64903",
                  MARKET_NAME: "틴베이크",
                  CATEGORY_SNO: "660",
                  CATEGORY_NAME: "과자/쿠키",
                  STANDARD_CATEGORY_SNO: "338",
                  STANDARD_CATEGORY_NAME: "과자/스낵",
                  DISCOUNT_RATE: 11,
                  SALES_PRICE: 3200,
                  SALES_PRICE_RANGE: "1~5,000",
                  IS_NEW: "0",
                  DELIVERY_TYPE: "standard",
                  IS_AD: "0",
                  LIST_PARAMS: null,
                  MARKET_TYPE_SNO: "2",
                  REVIEW_COUNT: 0,
                  REVIEW_COUNT_RANGE: "0",
                  REVIEW_RATING: 0,
                  LIKES_COUNT: 114,
                  LIKES_COUNT_RANGE: "101~150",
                  PROMOTION_TAG: ["FIRST_PURCHASE_BENEFIT"],
                  HAS_AWARD: false,
                  IS_ONLY_ABLY: false,
                  IMAGE_BADGE_LIST: [],
                  LIST_ID: "today_recommend",
                  LIST_INDEX: 4,
                },
              },
              render: {
                contents: ["PRICE", "NAME", "STORE", "NUDGING", "CHIPS"],
                size: "MEDIUM",
                data: {
                  image: {
                    url: "https://d3ha2047wt6x28.cloudfront.net/vPyruvzrNvY/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2ZiMjA3OTQ2ZGJlNGIxYTU0ZWJjMTE0OGU4OWFiZGRjLmpwZw",
                    use_animation: true,
                    ratio: 1.2,
                  },
                  name: "틴베이크 에이블리 팝업 라인업 14종 골라담기",
                  price: "3,200",
                  has_ad_badge: false,
                  name_lines: 1,
                  discount_rate: "11%",
                  closed_reason: null,
                  image_badge: null,
                  image_badge_width: null,
                  image_badge_height: null,
                  image_badge_list: [],
                  chips: [
                    {
                      meta: {
                        text_style: "subtitle6",
                        text_color: "#FF5160",
                        bg_color: "#FFEFF2",
                        border_color: "#FFEFF2",
                        border_width: 1,
                        rounded_corner_radius: 2,
                      },
                      name: "첫구매 혜택",
                      type: "DITTO_TEXT",
                    },
                  ],
                  store_text: "틴베이크",
                  nudging_text: "1,973개 구매중",
                  ranking: null,
                  actions: ["LIKE"],
                  discount_end_text: null,
                  top_nudging_text: null,
                  price_description: null,
                  today_delivery_order_deadline_time: null,
                },
              },
            },
          },
          {
            type: "GOODS_CARD",
            item_entity: {
              item: {
                sno: 25648592,
                name: "[골반커버🖤/모델극찬/기장선택] 사이드 스냅 3-way 와이드 코튼 핀턱 팬츠-4color",
                image:
                  "https://d3ha2047wt6x28.cloudfront.net/mcvjVxRZ_3c/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzZmNGRhYTUyN2Q5ODAyNTgzNTBjMzg5NWRlOWRlMzY1LmdpZg",
                market_sno: 1162,
                market_name: "모디무드",
                market_type: "쇼핑몰",
                delivery_type: "today",
                sell_count: 62581,
                discount_rate: 17,
                first_page_rendering: {
                  goods_name:
                    "[골반커버🖤/모델극찬/기장선택] 사이드 스냅 3-way 와이드 코튼 핀턱 팬츠-4color",
                  market_name: "모디무드",
                  cover_image:
                    "https://d3ha2047wt6x28.cloudfront.net/g75j-F5a-Pw/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjUwNTE2XzE3NDczODAxNTI0MzQ2NTZtLmpwZw",
                  market_image: null,
                  discount_rate: 17,
                  original_price: 29500,
                  price: 24220,
                },
                is_new: false,
                price: 24220,
                like: {
                  goods_sno: 25648592,
                  is_liked: false,
                  folder_sno: null,
                  referrer: {
                    list_id: "today_recommend",
                    list_index: 5,
                  },
                },
                ad: null,
                on_return: {
                  type: "INJECT",
                  data: {
                    url: "goods/25648592/recommend_related_goods_by_click_for_today/?from=TODAY",
                  },
                },
                category_name: "롱팬츠",
                feedback_type: "contain_icon",
                remote_deeplink: null,
              },
              logging: {
                ably_only_log: {
                  schema_name: "Goods",
                  list_id: "today_recommend",
                  list_index: 5,
                  pool: "best",
                  goods_sno: 25648592,
                },
                analytics: {
                  IS_COPY_TARGET_GOODS: false,
                  GOODS_SNO: "25648592",
                  GOODS_NAME:
                    "[골반커버🖤/모델극찬/기장선택] 사이드 스냅 3-way 와이드 코튼 핀턱 팬츠-4color",
                  MARKET_TYPE: "쇼핑몰",
                  MARKET_SNO: "1162",
                  MARKET_NAME: "모디무드",
                  CATEGORY_SNO: "176",
                  CATEGORY_NAME: "롱팬츠",
                  STANDARD_CATEGORY_SNO: "73",
                  STANDARD_CATEGORY_NAME: "롱팬츠",
                  DISCOUNT_RATE: 17,
                  SALES_PRICE: 24220,
                  SALES_PRICE_RANGE: "20,001~25,000",
                  IS_NEW: "0",
                  DELIVERY_TYPE: "today",
                  IS_AD: "0",
                  LIST_PARAMS: null,
                  MARKET_TYPE_SNO: "8",
                  REVIEW_COUNT: 8338,
                  REVIEW_COUNT_RANGE: "8,301~8,350",
                  REVIEW_RATING: 96,
                  LIKES_COUNT: 107375,
                  LIKES_COUNT_RANGE: "107,351~107,400",
                  PROMOTION_TAG: ["FIRST_PURCHASE_BENEFIT"],
                  HAS_AWARD: false,
                  IS_ONLY_ABLY: false,
                  IMAGE_BADGE_LIST: [
                    [
                      ["type", "TODAY_DELIVERY"],
                      [
                        "image_url",
                        "https://d3ha2047wt6x28.cloudfront.net/ed29a9GcSUo/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfdG9kYXlfZGVsaXZlcnkucG5n",
                      ],
                      ["image_width", 46],
                      ["image_height", 18],
                    ],
                  ],
                  LIST_ID: "today_recommend",
                  LIST_INDEX: 5,
                },
              },
              render: {
                contents: ["PRICE", "NAME", "STORE", "NUDGING", "CHIPS"],
                size: "MEDIUM",
                data: {
                  image: {
                    url: "https://d3ha2047wt6x28.cloudfront.net/mcvjVxRZ_3c/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzZmNGRhYTUyN2Q5ODAyNTgzNTBjMzg5NWRlOWRlMzY1LmdpZg",
                    use_animation: true,
                    ratio: 1.2,
                  },
                  name: "[골반커버🖤/모델극찬/기장선택] 사이드 스냅 3-way 와이드 코튼 핀턱 팬츠-4color",
                  price: "24,220",
                  has_ad_badge: false,
                  name_lines: 1,
                  discount_rate: "17%",
                  closed_reason: null,
                  image_badge:
                    "https://d3ha2047wt6x28.cloudfront.net/ed29a9GcSUo/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfdG9kYXlfZGVsaXZlcnkucG5n",
                  image_badge_width: 46,
                  image_badge_height: 18,
                  image_badge_list: [
                    {
                      type: "TODAY_DELIVERY",
                      image_url:
                        "https://d3ha2047wt6x28.cloudfront.net/ed29a9GcSUo/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfdG9kYXlfZGVsaXZlcnkucG5n",
                      image_width: 46,
                      image_height: 18,
                    },
                  ],
                  chips: [
                    {
                      meta: {
                        text_style: "subtitle6",
                        text_color: "#FF5160",
                        bg_color: "#FFEFF2",
                        border_color: "#FFEFF2",
                        border_width: 1,
                        rounded_corner_radius: 2,
                      },
                      name: "첫구매 혜택",
                      type: "DITTO_TEXT",
                    },
                  ],
                  store_text: "모디무드",
                  nudging_text: "62,581개 구매중",
                  ranking: null,
                  actions: ["LIKE"],
                  discount_end_text: null,
                  top_nudging_text: null,
                  price_description: null,
                  today_delivery_order_deadline_time: null,
                },
              },
            },
          },
          {
            type: "GOODS_CARD",
            item_entity: {
              item: {
                sno: 28638962,
                name: "[MADE/루즈핏]테일 스웨이드 차이나 크롭 자켓",
                image:
                  "https://d3ha2047wt6x28.cloudfront.net/5M0KsutaADQ/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2U1YjFmN2RjYmIxNjE1MWU2NTRjMzliOWZhOWRiMDkyLmdpZg",
                market_sno: 30537,
                market_name: "베이델리",
                market_type: "쇼핑몰",
                delivery_type: "today",
                sell_count: 21683,
                discount_rate: 13,
                first_page_rendering: {
                  goods_name: "[MADE/루즈핏]테일 스웨이드 차이나 크롭 자켓",
                  market_name: "베이델리",
                  cover_image:
                    "https://d3ha2047wt6x28.cloudfront.net/k5woja1KOBQ/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjUwNDI0XzE3NDU0ODI3OTkxMzUyMTJtLmpwZw",
                  market_image: null,
                  discount_rate: 13,
                  original_price: 59900,
                  price: 52110,
                },
                is_new: false,
                price: 52110,
                like: {
                  goods_sno: 28638962,
                  is_liked: false,
                  folder_sno: null,
                  referrer: {
                    list_id: "today_recommend",
                    list_index: 6,
                  },
                },
                ad: null,
                on_return: {
                  type: "INJECT",
                  data: {
                    url: "goods/28638962/recommend_related_goods_by_click_for_today/?from=TODAY",
                  },
                },
                category_name: "자켓",
                feedback_type: "contain_icon",
                remote_deeplink: null,
              },
              logging: {
                ably_only_log: {
                  schema_name: "Goods",
                  list_id: "today_recommend",
                  list_index: 6,
                  pool: "best",
                  goods_sno: 28638962,
                },
                analytics: {
                  IS_COPY_TARGET_GOODS: false,
                  GOODS_SNO: "28638962",
                  GOODS_NAME: "[MADE/루즈핏]테일 스웨이드 차이나 크롭 자켓",
                  MARKET_TYPE: "쇼핑몰",
                  MARKET_SNO: "30537",
                  MARKET_NAME: "베이델리",
                  CATEGORY_SNO: "293",
                  CATEGORY_NAME: "자켓",
                  STANDARD_CATEGORY_SNO: "4",
                  STANDARD_CATEGORY_NAME: "자켓",
                  DISCOUNT_RATE: 13,
                  SALES_PRICE: 52110,
                  SALES_PRICE_RANGE: "50,001~55,000",
                  IS_NEW: "0",
                  DELIVERY_TYPE: "today",
                  IS_AD: "0",
                  LIST_PARAMS: null,
                  MARKET_TYPE_SNO: "8",
                  REVIEW_COUNT: 2438,
                  REVIEW_COUNT_RANGE: "2,401~2,450",
                  REVIEW_RATING: 97,
                  LIKES_COUNT: 74256,
                  LIKES_COUNT_RANGE: "74,251~74,300",
                  PROMOTION_TAG: ["FIRST_PURCHASE_BENEFIT"],
                  HAS_AWARD: false,
                  IS_ONLY_ABLY: false,
                  IMAGE_BADGE_LIST: [
                    [
                      ["type", "TODAY_DELIVERY"],
                      [
                        "image_url",
                        "https://d3ha2047wt6x28.cloudfront.net/ed29a9GcSUo/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfdG9kYXlfZGVsaXZlcnkucG5n",
                      ],
                      ["image_width", 46],
                      ["image_height", 18],
                    ],
                  ],
                  LIST_ID: "today_recommend",
                  LIST_INDEX: 6,
                },
              },
              render: {
                contents: ["PRICE", "NAME", "STORE", "NUDGING", "CHIPS"],
                size: "MEDIUM",
                data: {
                  image: {
                    url: "https://d3ha2047wt6x28.cloudfront.net/5M0KsutaADQ/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2U1YjFmN2RjYmIxNjE1MWU2NTRjMzliOWZhOWRiMDkyLmdpZg",
                    use_animation: true,
                    ratio: 1.2,
                  },
                  name: "[MADE/루즈핏]테일 스웨이드 차이나 크롭 자켓",
                  price: "52,110",
                  has_ad_badge: false,
                  name_lines: 1,
                  discount_rate: "13%",
                  closed_reason: null,
                  image_badge:
                    "https://d3ha2047wt6x28.cloudfront.net/ed29a9GcSUo/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfdG9kYXlfZGVsaXZlcnkucG5n",
                  image_badge_width: 46,
                  image_badge_height: 18,
                  image_badge_list: [
                    {
                      type: "TODAY_DELIVERY",
                      image_url:
                        "https://d3ha2047wt6x28.cloudfront.net/ed29a9GcSUo/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfdG9kYXlfZGVsaXZlcnkucG5n",
                      image_width: 46,
                      image_height: 18,
                    },
                  ],
                  chips: [
                    {
                      meta: {
                        text_style: "subtitle6",
                        text_color: "#FF5160",
                        bg_color: "#FFEFF2",
                        border_color: "#FFEFF2",
                        border_width: 1,
                        rounded_corner_radius: 2,
                      },
                      name: "첫구매 혜택",
                      type: "DITTO_TEXT",
                    },
                  ],
                  store_text: "베이델리",
                  nudging_text: "21,683개 구매중",
                  ranking: null,
                  actions: ["LIKE"],
                  discount_end_text: null,
                  top_nudging_text: null,
                  price_description: null,
                  today_delivery_order_deadline_time: null,
                },
              },
            },
          },
          {
            type: "GOODS_CARD",
            item_entity: {
              item: {
                sno: 44980591,
                name: "[MADE/2기장/신상/묶음할인] 자체제작 기장선택 사계절 봄 여름 폴딩 사이드핀턱 와이드 롱 스웻팬츠 트레이닝팬츠 바지 체육대회 벚꽃 코디",
                image:
                  "https://d3ha2047wt6x28.cloudfront.net/wjkYfH2aYzE/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2E2Y2IxM2U5ZmI1ODk5MzRlMDM3ODU5MTVkNmVlMDQxLmdpZg",
                market_sno: 2308,
                market_name: "라이니",
                market_type: "셀럽",
                delivery_type: "today",
                sell_count: 63598,
                discount_rate: 30,
                first_page_rendering: {
                  goods_name:
                    "[MADE/2기장/신상/묶음할인] 자체제작 기장선택 사계절 봄 여름 폴딩 사이드핀턱 와이드 롱 스웻팬츠 트레이닝팬츠 바지 체육대회 벚꽃 코디",
                  market_name: "라이니",
                  cover_image:
                    "https://d3ha2047wt6x28.cloudfront.net/VvFOVc1S0QM/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjUwODIzXzE3NTU5MTYxOTAxMjYyMDNtLmpwZw",
                  market_image: null,
                  discount_rate: 30,
                  original_price: 16900,
                  price: 11800,
                },
                is_new: false,
                price: 11800,
                like: {
                  goods_sno: 44980591,
                  is_liked: false,
                  folder_sno: null,
                  referrer: {
                    list_id: "today_recommend",
                    list_index: 7,
                  },
                },
                ad: null,
                on_return: {
                  type: "INJECT",
                  data: {
                    url: "goods/44980591/recommend_related_goods_by_click_for_today/?from=TODAY",
                  },
                },
                category_name: "롱팬츠",
                feedback_type: "contain_icon",
                remote_deeplink: null,
              },
              logging: {
                ably_only_log: {
                  schema_name: "Goods",
                  list_id: "today_recommend",
                  list_index: 7,
                  pool: "best",
                  goods_sno: 44980591,
                },
                analytics: {
                  IS_COPY_TARGET_GOODS: false,
                  GOODS_SNO: "44980591",
                  GOODS_NAME:
                    "[MADE/2기장/신상/묶음할인] 자체제작 기장선택 사계절 봄 여름 폴딩 사이드핀턱 와이드 롱 스웻팬츠 트레이닝팬츠 바지 체육대회 벚꽃 코디",
                  MARKET_TYPE: "셀럽",
                  MARKET_SNO: "2308",
                  MARKET_NAME: "라이니",
                  CATEGORY_SNO: "176",
                  CATEGORY_NAME: "롱팬츠",
                  STANDARD_CATEGORY_SNO: "73",
                  STANDARD_CATEGORY_NAME: "롱팬츠",
                  DISCOUNT_RATE: 30,
                  SALES_PRICE: 11800,
                  SALES_PRICE_RANGE: "10,001~15,000",
                  IS_NEW: "0",
                  DELIVERY_TYPE: "today",
                  IS_AD: "0",
                  LIST_PARAMS: null,
                  MARKET_TYPE_SNO: "7",
                  REVIEW_COUNT: 10737,
                  REVIEW_COUNT_RANGE: "10,701~10,750",
                  REVIEW_RATING: 93,
                  LIKES_COUNT: 67118,
                  LIKES_COUNT_RANGE: "67,101~67,150",
                  PROMOTION_TAG: ["FIRST_PURCHASE_BENEFIT"],
                  HAS_AWARD: false,
                  IS_ONLY_ABLY: false,
                  IMAGE_BADGE_LIST: [
                    [
                      ["type", "TODAY_DELIVERY"],
                      [
                        "image_url",
                        "https://d3ha2047wt6x28.cloudfront.net/ed29a9GcSUo/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfdG9kYXlfZGVsaXZlcnkucG5n",
                      ],
                      ["image_width", 46],
                      ["image_height", 18],
                    ],
                  ],
                  LIST_ID: "today_recommend",
                  LIST_INDEX: 7,
                },
              },
              render: {
                contents: ["PRICE", "NAME", "STORE", "NUDGING", "CHIPS"],
                size: "MEDIUM",
                data: {
                  image: {
                    url: "https://d3ha2047wt6x28.cloudfront.net/wjkYfH2aYzE/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2E2Y2IxM2U5ZmI1ODk5MzRlMDM3ODU5MTVkNmVlMDQxLmdpZg",
                    use_animation: true,
                    ratio: 1.2,
                  },
                  name: "[MADE/2기장/신상/묶음할인] 자체제작 기장선택 사계절 봄 여름 폴딩 사이드핀턱 와이드 롱 스웻팬츠 트레이닝팬츠 바지 체육대회 벚꽃 코디",
                  price: "11,800",
                  has_ad_badge: false,
                  name_lines: 1,
                  discount_rate: "30%",
                  closed_reason: null,
                  image_badge:
                    "https://d3ha2047wt6x28.cloudfront.net/ed29a9GcSUo/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfdG9kYXlfZGVsaXZlcnkucG5n",
                  image_badge_width: 46,
                  image_badge_height: 18,
                  image_badge_list: [
                    {
                      type: "TODAY_DELIVERY",
                      image_url:
                        "https://d3ha2047wt6x28.cloudfront.net/ed29a9GcSUo/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfdG9kYXlfZGVsaXZlcnkucG5n",
                      image_width: 46,
                      image_height: 18,
                    },
                  ],
                  chips: [
                    {
                      meta: {
                        text_style: "subtitle6",
                        text_color: "#FF5160",
                        bg_color: "#FFEFF2",
                        border_color: "#FFEFF2",
                        border_width: 1,
                        rounded_corner_radius: 2,
                      },
                      name: "첫구매 혜택",
                      type: "DITTO_TEXT",
                    },
                  ],
                  store_text: "라이니",
                  nudging_text: "63,598개 구매중",
                  ranking: null,
                  actions: ["LIKE"],
                  discount_end_text: null,
                  top_nudging_text: null,
                  price_description: null,
                  today_delivery_order_deadline_time: null,
                },
              },
            },
          },
          {
            type: "GOODS_CARD",
            item_entity: {
              item: {
                sno: 52948204,
                name: "[MADE🤎가을ver./빅썬패치자수 포인트! 스웨이드골지 벌룬핏 와이드팬츠] 써니빅패치와이드팬츠",
                image:
                  "https://d3ha2047wt6x28.cloudfront.net/4g6mJLUYCNQ/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzZlMjJkYmY3YTJiNTVlYzQyZTY1ZDY3MTljMDMyMDAxLmdpZg",
                market_sno: 53093,
                market_name: "헤이나나",
                market_type: "셀럽",
                delivery_type: "standard",
                sell_count: 1945,
                discount_rate: 23,
                first_page_rendering: {
                  goods_name:
                    "[MADE🤎가을ver./빅썬패치자수 포인트! 스웨이드골지 벌룬핏 와이드팬츠] 써니빅패치와이드팬츠",
                  market_name: "헤이나나",
                  cover_image:
                    "https://d3ha2047wt6x28.cloudfront.net/xwBJk5yEI60/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjUwOTExXzE3NTc1ODAxNTU3MTY2NDdtLmpwZw",
                  market_image: null,
                  discount_rate: 23,
                  original_price: 20900,
                  price: 15900,
                },
                is_new: false,
                price: 15900,
                like: {
                  goods_sno: 52948204,
                  is_liked: false,
                  folder_sno: null,
                  referrer: {
                    list_id: "today_recommend",
                    list_index: 8,
                  },
                },
                ad: null,
                on_return: {
                  type: "INJECT",
                  data: {
                    url: "goods/52948204/recommend_related_goods_by_click_for_today/?from=TODAY",
                  },
                },
                category_name: "롱팬츠",
                feedback_type: "contain_icon",
                remote_deeplink: null,
              },
              logging: {
                ably_only_log: {
                  schema_name: "Goods",
                  list_id: "today_recommend",
                  list_index: 8,
                  pool: "best",
                  goods_sno: 52948204,
                },
                analytics: {
                  IS_COPY_TARGET_GOODS: false,
                  GOODS_SNO: "52948204",
                  GOODS_NAME:
                    "[MADE🤎가을ver./빅썬패치자수 포인트! 스웨이드골지 벌룬핏 와이드팬츠] 써니빅패치와이드팬츠",
                  MARKET_TYPE: "셀럽",
                  MARKET_SNO: "53093",
                  MARKET_NAME: "헤이나나",
                  CATEGORY_SNO: "176",
                  CATEGORY_NAME: "롱팬츠",
                  STANDARD_CATEGORY_SNO: "73",
                  STANDARD_CATEGORY_NAME: "롱팬츠",
                  DISCOUNT_RATE: 23,
                  SALES_PRICE: 15900,
                  SALES_PRICE_RANGE: "15,001~20,000",
                  IS_NEW: "0",
                  DELIVERY_TYPE: "standard",
                  IS_AD: "0",
                  LIST_PARAMS: null,
                  MARKET_TYPE_SNO: "7",
                  REVIEW_COUNT: 0,
                  REVIEW_COUNT_RANGE: "0",
                  REVIEW_RATING: 0,
                  LIKES_COUNT: 6611,
                  LIKES_COUNT_RANGE: "6,601~6,650",
                  PROMOTION_TAG: ["FIRST_PURCHASE_BENEFIT"],
                  HAS_AWARD: false,
                  IS_ONLY_ABLY: false,
                  IMAGE_BADGE_LIST: [],
                  LIST_ID: "today_recommend",
                  LIST_INDEX: 8,
                },
              },
              render: {
                contents: ["PRICE", "NAME", "STORE", "NUDGING", "CHIPS"],
                size: "MEDIUM",
                data: {
                  image: {
                    url: "https://d3ha2047wt6x28.cloudfront.net/4g6mJLUYCNQ/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzZlMjJkYmY3YTJiNTVlYzQyZTY1ZDY3MTljMDMyMDAxLmdpZg",
                    use_animation: true,
                    ratio: 1.2,
                  },
                  name: "[MADE🤎가을ver./빅썬패치자수 포인트! 스웨이드골지 벌룬핏 와이드팬츠] 써니빅패치와이드팬츠",
                  price: "15,900",
                  has_ad_badge: false,
                  name_lines: 1,
                  discount_rate: "23%",
                  closed_reason: null,
                  image_badge: null,
                  image_badge_width: null,
                  image_badge_height: null,
                  image_badge_list: [],
                  chips: [
                    {
                      meta: {
                        text_style: "subtitle6",
                        text_color: "#FF5160",
                        bg_color: "#FFEFF2",
                        border_color: "#FFEFF2",
                        border_width: 1,
                        rounded_corner_radius: 2,
                      },
                      name: "첫구매 혜택",
                      type: "DITTO_TEXT",
                    },
                  ],
                  store_text: "헤이나나",
                  nudging_text: "1,945개 구매중",
                  ranking: null,
                  actions: ["LIKE"],
                  discount_end_text: null,
                  top_nudging_text: null,
                  price_description: null,
                  today_delivery_order_deadline_time: null,
                },
              },
            },
          },
          {
            type: "GOODS_CARD",
            item_entity: {
              item: {
                sno: 52585676,
                name: "[도톰,아방!/꾸안꾸🤍] 지켜주고싶은 오버핏, 아메리칸 성조기 프린팅 투웨이 박시 루즈핏 후드집업 (5color)",
                image:
                  "https://d3ha2047wt6x28.cloudfront.net/LJLOnobrOWQ/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2RhYjM4YjRmNjc4YTA1ZjdhYzYxYmQ4ZWM0Nzk3NGM4LmdpZg",
                market_sno: 2466,
                market_name: "앤드모어",
                market_type: "셀럽",
                delivery_type: "shak",
                sell_count: 2429,
                discount_rate: 20,
                first_page_rendering: {
                  goods_name:
                    "[도톰,아방!/꾸안꾸🤍] 지켜주고싶은 오버핏, 아메리칸 성조기 프린팅 투웨이 박시 루즈핏 후드집업 (5color)",
                  market_name: "앤드모어",
                  cover_image:
                    "https://d3ha2047wt6x28.cloudfront.net/5IWpbSGk0dg/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjUwOTA0XzE3NTY5OTA0MDMzNDE3NjBtLmpwZw",
                  market_image: null,
                  discount_rate: 20,
                  original_price: 36900,
                  price: 29500,
                },
                is_new: false,
                price: 29500,
                like: {
                  goods_sno: 52585676,
                  is_liked: false,
                  folder_sno: null,
                  referrer: {
                    list_id: "today_recommend",
                    list_index: 9,
                  },
                },
                ad: null,
                on_return: {
                  type: "INJECT",
                  data: {
                    url: "goods/52585676/recommend_related_goods_by_click_for_today/?from=TODAY",
                  },
                },
                category_name: "집업/점퍼",
                feedback_type: "contain_icon",
                remote_deeplink: null,
              },
              logging: {
                ably_only_log: {
                  schema_name: "Goods",
                  list_id: "today_recommend",
                  list_index: 9,
                  pool: "best",
                  goods_sno: 52585676,
                },
                analytics: {
                  IS_COPY_TARGET_GOODS: false,
                  GOODS_SNO: "52585676",
                  GOODS_NAME:
                    "[도톰,아방!/꾸안꾸🤍] 지켜주고싶은 오버핏, 아메리칸 성조기 프린팅 투웨이 박시 루즈핏 후드집업 (5color)",
                  MARKET_TYPE: "셀럽",
                  MARKET_SNO: "2466",
                  MARKET_NAME: "앤드모어",
                  CATEGORY_SNO: "294",
                  CATEGORY_NAME: "집업/점퍼",
                  STANDARD_CATEGORY_SNO: "6",
                  STANDARD_CATEGORY_NAME: "집업",
                  DISCOUNT_RATE: 20,
                  SALES_PRICE: 29500,
                  SALES_PRICE_RANGE: "25,001~30,000",
                  IS_NEW: "0",
                  DELIVERY_TYPE: "shak",
                  IS_AD: "0",
                  LIST_PARAMS: null,
                  MARKET_TYPE_SNO: "7",
                  REVIEW_COUNT: 29,
                  REVIEW_COUNT_RANGE: "1~50",
                  REVIEW_RATING: 96,
                  LIKES_COUNT: 8789,
                  LIKES_COUNT_RANGE: "8,751~8,800",
                  PROMOTION_TAG: ["FIRST_PURCHASE_BENEFIT"],
                  HAS_AWARD: false,
                  IS_ONLY_ABLY: false,
                  IMAGE_BADGE_LIST: [
                    [
                      ["type", "TODAY_DELIVERY"],
                      [
                        "image_url",
                        "https://d3ha2047wt6x28.cloudfront.net/ed29a9GcSUo/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfdG9kYXlfZGVsaXZlcnkucG5n",
                      ],
                      ["image_width", 46],
                      ["image_height", 18],
                    ],
                  ],
                  LIST_ID: "today_recommend",
                  LIST_INDEX: 9,
                },
              },
              render: {
                contents: ["PRICE", "NAME", "STORE", "NUDGING", "CHIPS"],
                size: "MEDIUM",
                data: {
                  image: {
                    url: "https://d3ha2047wt6x28.cloudfront.net/LJLOnobrOWQ/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2RhYjM4YjRmNjc4YTA1ZjdhYzYxYmQ4ZWM0Nzk3NGM4LmdpZg",
                    use_animation: true,
                    ratio: 1.2,
                  },
                  name: "[도톰,아방!/꾸안꾸🤍] 지켜주고싶은 오버핏, 아메리칸 성조기 프린팅 투웨이 박시 루즈핏 후드집업 (5color)",
                  price: "29,500",
                  has_ad_badge: false,
                  name_lines: 1,
                  discount_rate: "20%",
                  closed_reason: null,
                  image_badge:
                    "https://d3ha2047wt6x28.cloudfront.net/ed29a9GcSUo/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfdG9kYXlfZGVsaXZlcnkucG5n",
                  image_badge_width: 46,
                  image_badge_height: 18,
                  image_badge_list: [
                    {
                      type: "TODAY_DELIVERY",
                      image_url:
                        "https://d3ha2047wt6x28.cloudfront.net/ed29a9GcSUo/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfdG9kYXlfZGVsaXZlcnkucG5n",
                      image_width: 46,
                      image_height: 18,
                    },
                  ],
                  chips: [
                    {
                      meta: {
                        text_style: "subtitle6",
                        text_color: "#FF5160",
                        bg_color: "#FFEFF2",
                        border_color: "#FFEFF2",
                        border_width: 1,
                        rounded_corner_radius: 2,
                      },
                      name: "첫구매 혜택",
                      type: "DITTO_TEXT",
                    },
                  ],
                  store_text: "앤드모어",
                  nudging_text: "2,429개 구매중",
                  ranking: null,
                  actions: ["LIKE"],
                  discount_end_text: null,
                  top_nudging_text: null,
                  price_description: null,
                  today_delivery_order_deadline_time: null,
                },
              },
            },
          },
          {
            type: "GOODS_CARD",
            item_entity: {
              item: {
                sno: 52175541,
                name: "[홀터나시SET] 유넥 티셔츠+나시 세트 통통제작",
                image:
                  "https://d3ha2047wt6x28.cloudfront.net/ZhfGu3EnhDE/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2IzNjdjZmVjYjBkMTk5NTBkM2EyMjY4ZWQ3MGQ4M2YyLmdpZg",
                market_sno: 9180,
                market_name: "통통",
                market_type: "셀럽",
                delivery_type: "standard",
                sell_count: 4407,
                discount_rate: 15,
                first_page_rendering: {
                  goods_name: "[홀터나시SET] 유넥 티셔츠+나시 세트 통통제작",
                  market_name: "통통",
                  cover_image:
                    "https://d3ha2047wt6x28.cloudfront.net/36FttYUkWzY/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjUwOTA4XzE3NTczMDY5MzA3NDc4MjNtLmpwZw",
                  market_image: null,
                  discount_rate: 15,
                  original_price: 19500,
                  price: 16500,
                },
                is_new: false,
                price: 16500,
                like: {
                  goods_sno: 52175541,
                  is_liked: false,
                  folder_sno: null,
                  referrer: {
                    list_id: "today_recommend",
                    list_index: 10,
                  },
                },
                ad: null,
                on_return: {
                  type: "INJECT",
                  data: {
                    url: "goods/52175541/recommend_related_goods_by_click_for_today/?from=TODAY",
                  },
                },
                category_name: "상의",
                feedback_type: "contain_icon",
                remote_deeplink: null,
              },
              logging: {
                ably_only_log: {
                  schema_name: "Goods",
                  list_id: "today_recommend",
                  list_index: 10,
                  pool: "best",
                  goods_sno: 52175541,
                },
                analytics: {
                  IS_COPY_TARGET_GOODS: false,
                  GOODS_SNO: "52175541",
                  GOODS_NAME: "[홀터나시SET] 유넥 티셔츠+나시 세트 통통제작",
                  MARKET_TYPE: "셀럽",
                  MARKET_SNO: "9180",
                  MARKET_NAME: "통통",
                  CATEGORY_SNO: "538",
                  CATEGORY_NAME: "상의",
                  STANDARD_CATEGORY_SNO: "124",
                  STANDARD_CATEGORY_NAME: "상의",
                  DISCOUNT_RATE: 15,
                  SALES_PRICE: 16500,
                  SALES_PRICE_RANGE: "15,001~20,000",
                  IS_NEW: "0",
                  DELIVERY_TYPE: "standard",
                  IS_AD: "0",
                  LIST_PARAMS: null,
                  MARKET_TYPE_SNO: "7",
                  REVIEW_COUNT: 20,
                  REVIEW_COUNT_RANGE: "1~50",
                  REVIEW_RATING: 100,
                  LIKES_COUNT: 10289,
                  LIKES_COUNT_RANGE: "10,251~10,300",
                  PROMOTION_TAG: ["FIRST_PURCHASE_BENEFIT"],
                  HAS_AWARD: false,
                  IS_ONLY_ABLY: true,
                  IMAGE_BADGE_LIST: [
                    [
                      ["type", "ONLY_ABLY"],
                      [
                        "image_url",
                        "https://d3ha2047wt6x28.cloudfront.net/lk7oDFuANYQ/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYWJseV9vbmx5LnBuZw",
                      ],
                      ["image_width", 58],
                      ["image_height", 18],
                    ],
                  ],
                  LIST_ID: "today_recommend",
                  LIST_INDEX: 10,
                },
              },
              render: {
                contents: ["PRICE", "NAME", "STORE", "NUDGING", "CHIPS"],
                size: "MEDIUM",
                data: {
                  image: {
                    url: "https://d3ha2047wt6x28.cloudfront.net/ZhfGu3EnhDE/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2IzNjdjZmVjYjBkMTk5NTBkM2EyMjY4ZWQ3MGQ4M2YyLmdpZg",
                    use_animation: true,
                    ratio: 1.2,
                  },
                  name: "[홀터나시SET] 유넥 티셔츠+나시 세트 통통제작",
                  price: "16,500",
                  has_ad_badge: false,
                  name_lines: 1,
                  discount_rate: "15%",
                  closed_reason: null,
                  image_badge: null,
                  image_badge_width: null,
                  image_badge_height: null,
                  image_badge_list: [
                    {
                      type: "ONLY_ABLY",
                      image_url:
                        "https://d3ha2047wt6x28.cloudfront.net/lk7oDFuANYQ/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYWJseV9vbmx5LnBuZw",
                      image_width: 58,
                      image_height: 18,
                    },
                  ],
                  chips: [
                    {
                      meta: {
                        text_style: "subtitle6",
                        text_color: "#FF5160",
                        bg_color: "#FFEFF2",
                        border_color: "#FFEFF2",
                        border_width: 1,
                        rounded_corner_radius: 2,
                      },
                      name: "첫구매 혜택",
                      type: "DITTO_TEXT",
                    },
                  ],
                  store_text: "통통",
                  nudging_text: "4,407개 구매중",
                  ranking: null,
                  actions: ["LIKE"],
                  discount_end_text: null,
                  top_nudging_text: null,
                  price_description: null,
                  today_delivery_order_deadline_time: null,
                },
              },
            },
          },
          {
            type: "GOODS_CARD",
            item_entity: {
              item: {
                sno: 52768246,
                name: "아메리칸 스타에이트 오버핏 후디_5colors",
                image:
                  "https://d3ha2047wt6x28.cloudfront.net/A13STmReQqQ/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzg2YWZkZWZhNjQxNGEwYjRkY2I3Y2MwZGJhN2FiODRlLmdpZg",
                market_sno: 16068,
                market_name: "위티인벤",
                market_type: "캐주얼 브랜드",
                delivery_type: "standard",
                sell_count: 928,
                discount_rate: 40,
                first_page_rendering: {
                  goods_name: "아메리칸 스타에이트 오버핏 후디_5colors",
                  market_name: " 위티인벤",
                  cover_image:
                    "https://d3ha2047wt6x28.cloudfront.net/aI2OCO2yEP0/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzg2YWZkZWZhNjQxNGEwYjRkY2I3Y2MwZGJhN2FiODRlLmdpZg",
                  market_image: null,
                  discount_rate: 40,
                  original_price: 48900,
                  price: 29340,
                },
                is_new: false,
                price: 29340,
                like: {
                  goods_sno: 52768246,
                  is_liked: false,
                  folder_sno: null,
                  referrer: {
                    list_id: "today_recommend",
                    list_index: 11,
                  },
                },
                ad: null,
                on_return: {
                  type: "INJECT",
                  data: {
                    url: "goods/52768246/recommend_related_goods_by_click_for_today/?from=TODAY",
                  },
                },
                category_name: "후드",
                feedback_type: "contain_icon",
                remote_deeplink: null,
              },
              logging: {
                ably_only_log: {
                  schema_name: "Goods",
                  list_id: "today_recommend",
                  list_index: 11,
                  pool: "best",
                  goods_sno: 52768246,
                },
                analytics: {
                  IS_COPY_TARGET_GOODS: false,
                  GOODS_SNO: "52768246",
                  GOODS_NAME: "아메리칸 스타에이트 오버핏 후디_5colors",
                  MARKET_TYPE: "캐주얼 브랜드",
                  MARKET_SNO: "16068",
                  MARKET_NAME: "위티인벤",
                  CATEGORY_SNO: "500",
                  CATEGORY_NAME: "후드",
                  STANDARD_CATEGORY_SNO: "26",
                  STANDARD_CATEGORY_NAME: "후드",
                  DISCOUNT_RATE: 40,
                  SALES_PRICE: 29340,
                  SALES_PRICE_RANGE: "25,001~30,000",
                  IS_NEW: "0",
                  DELIVERY_TYPE: "standard",
                  IS_AD: "0",
                  LIST_PARAMS: null,
                  MARKET_TYPE_SNO: "12",
                  REVIEW_COUNT: 5,
                  REVIEW_COUNT_RANGE: "1~50",
                  REVIEW_RATING: 80,
                  LIKES_COUNT: 3267,
                  LIKES_COUNT_RANGE: "3,251~3,300",
                  PROMOTION_TAG: ["FIRST_PURCHASE_BENEFIT"],
                  HAS_AWARD: false,
                  IS_ONLY_ABLY: false,
                  IMAGE_BADGE_LIST: [],
                  LIST_ID: "today_recommend",
                  LIST_INDEX: 11,
                  BRAND_SNO: 12985,
                  BRAND_NAME: "위티인벤",
                },
              },
              render: {
                contents: ["PRICE", "NAME", "STORE", "NUDGING", "CHIPS"],
                size: "MEDIUM",
                data: {
                  image: {
                    url: "https://d3ha2047wt6x28.cloudfront.net/A13STmReQqQ/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzg2YWZkZWZhNjQxNGEwYjRkY2I3Y2MwZGJhN2FiODRlLmdpZg",
                    use_animation: true,
                    ratio: 1.2,
                  },
                  name: "아메리칸 스타에이트 오버핏 후디_5colors",
                  price: "29,340",
                  has_ad_badge: false,
                  name_lines: 1,
                  discount_rate: "40%",
                  closed_reason: null,
                  image_badge: null,
                  image_badge_width: null,
                  image_badge_height: null,
                  image_badge_list: [],
                  chips: [
                    {
                      meta: {
                        text_style: "subtitle6",
                        text_color: "#FF5160",
                        bg_color: "#FFEFF2",
                        border_color: "#FFEFF2",
                        border_width: 1,
                        rounded_corner_radius: 2,
                      },
                      name: "첫구매 혜택",
                      type: "DITTO_TEXT",
                    },
                  ],
                  store_text: "<font color='#6093FC'>브랜드</font> 위티인벤",
                  nudging_text: "928개 구매중",
                  ranking: null,
                  actions: ["LIKE"],
                  discount_end_text: null,
                  top_nudging_text: null,
                  price_description: null,
                  today_delivery_order_deadline_time: null,
                },
              },
            },
          },
          {
            type: "GOODS_CARD",
            item_entity: {
              item: {
                sno: 27966224,
                name: "[브라운추가/숏,롱] 널디앤 옆절개 트임 핀턱 바지 롱 와이드 데일리 트레이닝 밴딩 팬츠",
                image:
                  "https://d3ha2047wt6x28.cloudfront.net/8SBe62gb8UM/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2Y1NDlkZGMyZmQ4MDcwYzQ2NmY1MjU3NzM2YTMyY2M4LmdpZg",
                market_sno: 10071,
                market_name: "조이조이",
                market_type: "셀럽",
                delivery_type: "today",
                sell_count: 148435,
                discount_rate: 53,
                first_page_rendering: {
                  goods_name:
                    "[브라운추가/숏,롱] 널디앤 옆절개 트임 핀턱 바지 롱 와이드 데일리 트레이닝 밴딩 팬츠",
                  market_name: "조이조이",
                  cover_image:
                    "https://d3ha2047wt6x28.cloudfront.net/pg7tYLfxM7o/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjUwOTE4XzE3NTgxNjM4NjI0ODkwNjhtLmpwZw",
                  market_image: null,
                  discount_rate: 53,
                  original_price: 28900,
                  price: 13520,
                },
                is_new: false,
                price: 13520,
                like: {
                  goods_sno: 27966224,
                  is_liked: false,
                  folder_sno: null,
                  referrer: {
                    list_id: "today_recommend",
                    list_index: 12,
                  },
                },
                ad: null,
                on_return: {
                  type: "INJECT",
                  data: {
                    url: "goods/27966224/recommend_related_goods_by_click_for_today/?from=TODAY",
                  },
                },
                category_name: "롱팬츠",
                feedback_type: "contain_icon",
                remote_deeplink: null,
              },
              logging: {
                ably_only_log: {
                  schema_name: "Goods",
                  list_id: "today_recommend",
                  list_index: 12,
                  pool: "best",
                  goods_sno: 27966224,
                },
                analytics: {
                  IS_COPY_TARGET_GOODS: false,
                  GOODS_SNO: "27966224",
                  GOODS_NAME:
                    "[브라운추가/숏,롱] 널디앤 옆절개 트임 핀턱 바지 롱 와이드 데일리 트레이닝 밴딩 팬츠",
                  MARKET_TYPE: "셀럽",
                  MARKET_SNO: "10071",
                  MARKET_NAME: "조이조이",
                  CATEGORY_SNO: "176",
                  CATEGORY_NAME: "롱팬츠",
                  STANDARD_CATEGORY_SNO: "73",
                  STANDARD_CATEGORY_NAME: "롱팬츠",
                  DISCOUNT_RATE: 53,
                  SALES_PRICE: 13520,
                  SALES_PRICE_RANGE: "10,001~15,000",
                  IS_NEW: "0",
                  DELIVERY_TYPE: "today",
                  IS_AD: "0",
                  LIST_PARAMS: null,
                  MARKET_TYPE_SNO: "7",
                  REVIEW_COUNT: 30502,
                  REVIEW_COUNT_RANGE: "30,501~30,550",
                  REVIEW_RATING: 95,
                  LIKES_COUNT: 128478,
                  LIKES_COUNT_RANGE: "128,451~128,500",
                  PROMOTION_TAG: ["FIRST_PURCHASE_BENEFIT"],
                  HAS_AWARD: false,
                  IS_ONLY_ABLY: false,
                  IMAGE_BADGE_LIST: [
                    [
                      ["type", "TODAY_DELIVERY"],
                      [
                        "image_url",
                        "https://d3ha2047wt6x28.cloudfront.net/ed29a9GcSUo/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfdG9kYXlfZGVsaXZlcnkucG5n",
                      ],
                      ["image_width", 46],
                      ["image_height", 18],
                    ],
                  ],
                  LIST_ID: "today_recommend",
                  LIST_INDEX: 12,
                },
              },
              render: {
                contents: ["PRICE", "NAME", "STORE", "NUDGING", "CHIPS"],
                size: "MEDIUM",
                data: {
                  image: {
                    url: "https://d3ha2047wt6x28.cloudfront.net/8SBe62gb8UM/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2Y1NDlkZGMyZmQ4MDcwYzQ2NmY1MjU3NzM2YTMyY2M4LmdpZg",
                    use_animation: true,
                    ratio: 1.2,
                  },
                  name: "[브라운추가/숏,롱] 널디앤 옆절개 트임 핀턱 바지 롱 와이드 데일리 트레이닝 밴딩 팬츠",
                  price: "13,520",
                  has_ad_badge: false,
                  name_lines: 1,
                  discount_rate: "53%",
                  closed_reason: null,
                  image_badge:
                    "https://d3ha2047wt6x28.cloudfront.net/ed29a9GcSUo/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfdG9kYXlfZGVsaXZlcnkucG5n",
                  image_badge_width: 46,
                  image_badge_height: 18,
                  image_badge_list: [
                    {
                      type: "TODAY_DELIVERY",
                      image_url:
                        "https://d3ha2047wt6x28.cloudfront.net/ed29a9GcSUo/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfdG9kYXlfZGVsaXZlcnkucG5n",
                      image_width: 46,
                      image_height: 18,
                    },
                  ],
                  chips: [
                    {
                      meta: {
                        text_style: "subtitle6",
                        text_color: "#FF5160",
                        bg_color: "#FFEFF2",
                        border_color: "#FFEFF2",
                        border_width: 1,
                        rounded_corner_radius: 2,
                      },
                      name: "첫구매 혜택",
                      type: "DITTO_TEXT",
                    },
                  ],
                  store_text: "조이조이",
                  nudging_text: "148,435개 구매중",
                  ranking: null,
                  actions: ["LIKE"],
                  discount_end_text: null,
                  top_nudging_text: null,
                  price_description: null,
                  today_delivery_order_deadline_time: null,
                },
              },
            },
          },
        ],
        footer: null,
      },
    },
  ],
  next_token: "eyJsaSI6IDIsICJuIjogImV5SnNZWE4wWDJsdVpHVjRJam9nTVROOSJ9",
  view_event_channels: [
    "firebase",
    "amplitude",
    "ablylog",
    "facebook",
    "appsflyer",
  ],
};

// 옷 이름, 브랜드 마켓 이름, 판매된 수

// const entities = data.components.map((v) => ({
//   name: v.name,
//   market_name: v.market_name,
//   sell_count: v.sell_count,
// }));
// console.log(a1);

// const entities = data.components
//   .map((v) => {
//     v.entity;
//   })
//   .map((v) => v.item_list)
//   .filter((v) => v.length > 1)
//   .filter((v) => v.some((x) => x.type))
//   .flat()
//   .map((v) => v.item_entity.item)
//   .map((v) => ({
//     name: v.name,
//     market_name: v.market_name,
//     sell_count: sell_count,
//   }));

// const a6 = data.components
//   .map((v) => v.entity.item_list)
//   .flat()
//   .filter((v) => v.type)
//   .map((v) => v.item_entity.item)
//   .map((v) => ({
//     name: v.name,
//     market_name: v.market_name,
//     sell_count: v.sell_count,
//   }));

const a6 = data.components
  .map((v) => v.entity.item_list)
  .flat()
  .filter((v) => v.type);
console.log(a6);
